leftnav:
- identifier: 484606be-418d-4457-92e6-094d006eddc4
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 1c2e1efe-1f53-48bc-84b6-8fc9d63a10af
  name: Instructor Insights
  pageRef: /pages/insturctor-insights
  weight: 20
- identifier: 6aa1aeb3-5bed-41ab-b548-0e57cc32fdf8
  name: Kanji Video Lectures
  pageRef: /video_galleries/kanji-video-lectures
  weight: 30
